# Generated by Django 3.2.9 on 2022-01-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=50)),
                ('date_of_birth', models.DateField(max_length=10)),
                ('mobile_number', models.CharField(max_length=12)),
            ],
        ),
    ]
